# Generated by Django 5.2.12 on 2026-03-13 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(max_length=10)),
                ('browser', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('is_bot', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('referrer', models.URLField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session_hash',), name='unique_session_hash')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, default='', max_length=300)),
                ('time_on_page_seconds', models.FloatField(blank=True, null=True)),
                ('referrer_path', models.CharField(blank=True, default='', max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.session')),
            ],
            options={
                'indexes': [models.Index(fields=['viewed_at'], name='analytics_p_viewed__6302cc_idx'), models.Index(fields=['path'], name='analytics_p_path_3382b5_idx')],
            },
        ),
    ]
