# Generated by Django 5.2.12 on 2026-03-16 21:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_upgrade_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], max_length=10)),
                ('event', models.CharField(max_length=30)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=10)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='analytics_p_path_06b4a4_idx',
            old_name='analytics_pv_path_date_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='analytics_s_started_0e04d8_idx',
            old_name='analytics_s_started_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='analytics_s_referre_ee3960_idx',
            old_name='analytics_s_ref_dom_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='analytics_s_device__697802_idx',
            old_name='analytics_s_device_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='analytics_s_is_bot_1cfcc9_idx',
            old_name='analytics_s_is_bot_idx',
        ),
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='authevent',
            index=models.Index(fields=['created_at'], name='analytics_a_created_e54eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='authevent',
            index=models.Index(fields=['provider', 'outcome'], name='analytics_a_provide_f7cf1d_idx'),
        ),
    ]
