# Generated by Django 5.2.12 on 2026-03-07 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='resumes/')),
                ('file_type', models.CharField(max_length=10)),
                ('parsed_data', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('key_projects', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('story_hook', models.TextField(blank=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
