# Generated by Django 5.2.12 on 2026-03-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachmessage',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='outreachmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
