# Generated by Django 5.2.12 on 2026-03-07 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_login', models.CharField(max_length=100, unique=True)),
                ('github_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('blog', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('public_repos_count', models.IntegerField(default=0)),
                ('github_url', models.URLField(blank=True)),
                ('careers_url', models.URLField(blank=True)),
                ('linkedin_search_url', models.URLField(blank=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['github_login'], name='prospects_o_github__a50e05_idx'), models.Index(fields=['github_id'], name='prospects_o_github__dc151c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('is_fork', models.BooleanField(default=False)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('languages', models.JSONField(default=dict)),
                ('has_claude_md', models.BooleanField(default=False)),
                ('has_cursor_config', models.BooleanField(default=False)),
                ('has_copilot_config', models.BooleanField(default=False)),
                ('has_windsurf_config', models.BooleanField(default=False)),
                ('has_docker', models.BooleanField(default=False)),
                ('has_ci_cd', models.BooleanField(default=False)),
                ('has_tests', models.BooleanField(default=False)),
                ('has_deployment_config', models.BooleanField(default=False)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_github', models.DateTimeField(blank=True, null=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='prospects.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RepoContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=100)),
                ('github_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('blog', models.URLField(blank=True)),
                ('twitter_username', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
                ('contributions', models.IntegerField(default=0)),
                ('profile_url', models.URLField(blank=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='prospects.organizationrepo')),
            ],
        ),
        migrations.CreateModel(
            name='RepoStackDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('ai_ml', 'AI/ML'), ('database', 'Database'), ('infrastructure', 'Infrastructure'), ('ai_tool', 'AI Tool')], max_length=50)),
                ('source_file', models.CharField(max_length=200)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_detections', to='prospects.organizationrepo')),
            ],
        ),
        migrations.CreateModel(
            name='SavedProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('researched', 'Researched'), ('contacted', 'Contacted'), ('interviewing', 'Interviewing'), ('passed', 'Passed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='prospects.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_prospects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='organizationrepo',
            index=models.Index(fields=['organization'], name='prospects_o_organiz_c91b09_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationrepo',
            index=models.Index(fields=['github_id'], name='prospects_o_github__c94f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationrepo',
            index=models.Index(fields=['full_name'], name='prospects_o_full_na_fc9eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='repocontributor',
            index=models.Index(fields=['github_username'], name='prospects_r_github__226e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='repocontributor',
            index=models.Index(fields=['repo'], name='prospects_r_repo_id_39ca6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repostackdetection',
            unique_together={('repo', 'technology_name')},
        ),
        migrations.AlterUniqueTogether(
            name='savedprospect',
            unique_together={('user', 'organization')},
        ),
    ]
