# Generated by Django 5.2.12 on 2026-03-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedprospect',
            options={'ordering': ['-created_at']},
        ),
    ]
