# Generated by Django 5.2.12 on 2026-03-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_alter_savedprospect_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrepo',
            name='has_aider_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_amazonq_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_bolt_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_cline_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_codeium_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_codex_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_continue_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_idx_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_lovable_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_roo_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='has_v0_config',
            field=models.BooleanField(default=False),
        ),
    ]
