# Generated by Django 5.2.12 on 2026-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_add_expanded_ai_tool_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrepo',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='ai_analysis_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='ai_analysis_status',
            field=models.CharField(choices=[('none', 'Not analyzed'), ('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationrepo',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
