# Generated by Django 5.2.12 on 2026-03-07 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('endpoint', models.CharField(max_length=100)),
                ('domain_searched', models.CharField(max_length=200)),
                ('credits_used', models.DecimalField(decimal_places=1, max_digits=5)),
                ('results_returned', models.IntegerField(default=0)),
                ('cached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('hunter', 'Hunter.io'), ('apollo', 'Apollo.io'), ('github', 'GitHub')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('email_confidence', models.IntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('seniority', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_engineering_lead', models.BooleanField(default=False)),
                ('source_domain', models.CharField(max_length=200)),
                ('last_enriched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='prospects.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='enrichment__organiz_15d369_idx'), models.Index(fields=['email'], name='enrichment__email_78f13d_idx'), models.Index(fields=['is_engineering_lead'], name='enrichment__is_engi_72af72_idx')],
            },
        ),
    ]
