# Generated by Django 5.2.12 on 2026-03-26 21:32

from django.db import migrations


def promote_admin(apps, schema_editor):
    User = apps.get_model("auth", "User")
    try:
        user = User.objects.get(email="mnraynor90@gmail.com")
        user.is_staff = True
        user.is_superuser = True
        user.save(update_fields=["is_staff", "is_superuser"])
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(promote_admin, migrations.RunPython.noop),
    ]
