# Generated by Django 5.2.12 on 2026-03-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='atsmapping',
            new_name='jobs_atsmap_organiz_ddb018_idx',
            old_name='jobs_atsmap_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='atsmapping',
            new_name='jobs_atsmap_is_veri_1d4a61_idx',
            old_name='jobs_atsmap_is_veri_idx',
        ),
        migrations.RenameIndex(
            model_name='joblisting',
            new_name='jobs_joblis_is_acti_861fa0_idx',
            old_name='jobs_joblis_is_acti_idx',
        ),
    ]
