# Generated by Django 5.2.12 on 2026-03-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_atsmap_organiz_idx_jobs_atsmap_organiz_ddb018_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joblisting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='source',
            field=models.CharField(choices=[('ats', 'ATS Board'), ('remoteok', 'RemoteOK'), ('remotive', 'Remotive'), ('wwr', 'We Work Remotely'), ('hn', "HackerNews Who's Hiring")], default='ats', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='ats_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.atsmapping'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['source'], name='jobs_joblis_source_8b426c_idx'),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.UniqueConstraint(condition=models.Q(('ats_mapping__isnull', False)), fields=('ats_mapping', 'external_id'), name='unique_ats_job'),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.UniqueConstraint(condition=models.Q(('ats_mapping__isnull', True)), fields=('source', 'external_id'), name='unique_external_job'),
        ),
    ]
